name: apex-bot
services:
  - environment_slug: node-js
    github:
      repo: junyihuang168/apex-bot
      branch: main
      deploy_on_push: true
    name: apex-bot
    build_command: "npm install"
    run_command: "npm start"
    http_port: 8080
